[package]
name = "brainfsym-web"
version = "0.1.0"
authors = ["Benjamin Levy <blevy@protonmail.com>"]
edition = "2018"

[dependencies]
brainfsym = { path = "../lib" }
yew = { version = "0.14.3", features = ["std_web"] }
